name: gcp-afd
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
- name: inspec-gcp
  url: https://github.com/inspec/inspec-gcp/archive/master.tar.gz
supports:
- platform: "gcp"
- platform: "unix"
- platform: "windows"
- platform: "macos"